# Generated by Django 4.2.30 on 2026-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('job_title_role', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title_levels', models.JSONField(default=list)),
                ('job_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_company_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('job_company_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('inferred_years_experience', models.FloatField(blank=True, null=True)),
                ('linkedin_connections', models.FloatField(blank=True, null=True)),
                ('emails', models.JSONField(default=list)),
                ('phone_numbers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='search_prof_full_na_1d998d_idx'), models.Index(fields=['job_title'], name='search_prof_job_tit_100ec8_idx'), models.Index(fields=['location_country'], name='search_prof_locatio_717f42_idx')],
            },
        ),
    ]
